another attempt at fixing fab driver path issues

diff --git a/bin/setup_prereqs b/bin/setup_prereqs
--- a/bin/setup_prereqs
+++ b/bin/setup_prereqs
@@ -24,7 +24,10 @@ if [ ! -d $O_DIR/python_environment/sensing_home ]; then
   python -m venv sensing_home
 fi
 
-source $O_DIR/python_environment/sensing_home/bin/activate
+echo "source \"$O_DIR/python_environment/sensing_home/bin/activate\""
+source "$O_DIR/python_environment/sensing_home/bin/activate"
+
+python -m pip install "pip>=21.2"
 
 PIP_FREEZE=$(python -m pip freeze)
 
@@ -54,6 +57,7 @@ else
     fi
   done <<< "$CLANG_PY_AVAIL"
   if [ -z "${CLANG_PY_TARGET}" ]; then
+    echo "[ERROR] Clang Python version not found."
     exit 1
   fi
   CLANG_PY_SELECT=$(echo "$CLANG_PY_IDXVER" | grep "$CLANG_PY_TARGET" | head -1)
@@ -76,6 +80,14 @@ MATPLOTLIB_TEST=$(echo "$PIP_FREEZE" | grep "matplotlib" >/dev/null; echo $?)
 if [ "$MATPLOTLIB_TEST" -eq "0" ]; then
   echo "Matplotlib is installed"
 else
+  LIBJPEGDEV_INSTALLED=$(echo "$DPKG_L" | grep -E 'libjpeg-dev(:|\s)\s' >/dev/null; echo $?)
+
+  if [ "$LIBJPEGDEV_INSTALLED" -eq "0" ]; then
+    echo "libjpeg-dev is installed"
+  else
+    echo "libjpeg-dev is not installed. Installing now"
+    sudo apt-get install libjpeg-dev
+  fi
   echo "Matplotlib is not installed. Installing now"
   python -m pip install matplotlib
 fi
